// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtnnjJX8i6LbHnraiptPzrNOdXDvze_ok',
    appId: '1:90014662135:android:7cd425d3734cadfc3582f2',
    messagingSenderId: '90014662135',
    projectId: 'stressbuster-7b405',
    authDomain: 'stressbuster-7b405.firebaseapp.com',
    storageBucket: 'stressbuster-7b405.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtnnjJX8i6LbHnraiptPzrNOdXDvze_ok',
    appId: '1:90014662135:android:7cd425d3734cadfc3582f2',
    messagingSenderId: '90014662135',
    projectId: 'stressbuster-7b405',
    storageBucket: 'stressbuster-7b405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtnnjJX8i6LbHnraiptPzrNOdXDvze_ok',
    appId: '1:90014662135:android:7cd425d3734cadfc3582f2',
    messagingSenderId: '90014662135',
    projectId: 'stressbuster-7b405',
    storageBucket: 'stressbuster-7b405.appspot.com',
    iosClientId: '',
    iosBundleId: 'com.stressbuster.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtnnjJX8i6LbHnraiptPzrNOdXDvze_ok',
    appId: '1:90014662135:android:7cd425d3734cadfc3582f2',
    messagingSenderId: '90014662135',
    projectId: 'stressbuster-7b405',
    storageBucket: 'stressbuster-7b405.appspot.com',
    iosClientId: '',
    iosBundleId: 'com.stressbuster.app',
  );
}
